### ISSUE TITLE
Add traditional flat scope examples to Resources section

### ISSUE THREAD

**Issue by dmitrizagidulin** [bspk/oauth.xyz-site#10]
For existing use cases that are using traditional OAuth2 flat scopes, it would be useful to add examples of how that would be handled to the Resources section of the Request page.

I vaguely recall that you mentioned that the `resources:` section of the request could mix together "flat"/traditional scopes and the newer structured scopes? Does that mean that this would be a valid request (if I want to mix the two modes):

```
POST /transaction
{
  resources: [
    "id_token",
    {
        "actions": [ "read", "write ],
        "resources": [ /* .. */ ]
    },
    "scope2"
  ],
  interact: { /* .. */ },
  display_client: { /* .. */ }
}
```

(if I wanted to request an OIDC style id_token (possibly with embedded Verifiable Credentials etc))

**Comment by jricher** [comment]
Yes, that's on the main request page example under the "both" option for resources:

```
{
    "resources": [
        {
            "actions": [
                "read",
                "write",
                "dolphin"
            ],
            "locations": [
                "https://server.example.net/",
                "https://resource.local/other"
            ],
            "datatypes": [
                "metadata",
                "images"
            ]
        },
        "dolphin-metadata"
    ],
    "interact": {
        "redirect": true,
        "callback": {
            "uri": "https://client.example.net/return/123455",
            "nonce": "LKLTI25DK82FX4T4QFZC"
        }
    },
    "display": {
        "name": "My Client Display Name",
        "uri": "https://example.net/client"
    }
}
```

This example combines the `dolphin-metadata` example "scope", which is actually a "resource handle" in XYZ parlance, with the full resource object.

**Comment by dmitrizagidulin** [comment]
Got it, thanks!
